### ISSUE TITLE
Accessing mysql rcdb from offsite

### ISSUE THREAD

**Issue by mikestaib** [JeffersonLab/rcdb#34]
I'm running into problems connecting to the RCDB from offsite. I can connect to the database directly with mysql, but using the python rcdb connection doesn't seem to work. This command works fine at JLab, but produces the following error from offsite (confirmed by Sean):

`python $RCDB_HOME/python/example_simple_queries.py mysql://rcdb@hallddb.jlab.org/rcdb`

output:

`['/home/mstaib/builds/rcdb/python/example_simple_queries.py', 'mysql://rcdb@hallddb.jlab.org/rcdb']
Traceback (most recent call last):
  File "/home/mstaib/builds/rcdb/python/example_simple_queries.py", line 23, in <module>
    db = RCDBProvider(args.connection_string)
  File "/home/mstaib/builds/rcdb/python/rcdb/provider.py", line 58, in __init__
    self.connect(connection_string, check_version)
  File "/home/mstaib/builds/rcdb/python/rcdb/provider.py", line 110, in connect
    if not self.is_acceptable_sql_version():
  File "/home/mstaib/builds/rcdb/python/rcdb/provider.py", line 68, in is_acceptable_sql_version
    .filter(SchemaVersion.version == rcdb.SQL_SCHEMA_VERSION)
  File "/home/mstaib/builds/rcdb/python/sqlalchemy/orm/query.py", line 2724, in scalar
    ret = self.one()
  File "/home/mstaib/builds/rcdb/python/sqlalchemy/orm/query.py", line 2693, in one
    ret = list(self)
  File "/home/mstaib/builds/rcdb/python/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/home/mstaib/builds/rcdb/python/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/mstaib/builds/rcdb/python/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/mstaib/builds/rcdb/python/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/mstaib/builds/rcdb/python/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/mstaib/builds/rcdb/python/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/mstaib/builds/rcdb/python/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/mstaib/builds/rcdb/python/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/mstaib/builds/rcdb/python/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/mstaib/builds/rcdb/python/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/home/mstaib/builds/rcdb/python/mysql/connector/cursor.py", line 491, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/home/mstaib/builds/rcdb/python/mysql/connector/connection.py", line 635, in cmd_query
    statement))
  File "/home/mstaib/builds/rcdb/python/mysql/connector/connection.py", line 553, in _handle_result
    raise errors.get_exception(packet)
sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'rcdb.schema_versions' doesn't exist [SQL: 'SELECT count(schema_versions.version) AS count_1 \nFROM schema_versions \nWHERE schema_versions.version = %(version_1)s'] [parameters: {'version_1': 1}]`

**Comment by sdobbs** [comment]
@markito3 can you confirm that the RCDB replication to hallddb is working properly?

**Comment by sdobbs** [comment]
Actually, i just tried to modify the DB from onsite, and also got a schema error.  Maybe something in the DB changed?

**Comment by markito3** [comment]
from the counting house? or from the computer center?

On 05/25/2016 01:46 PM, Sean Dobbs wrote:
>
> Actually, i just tried to modify the DB from onsite, and also got a 
> schema error. Maybe something in the DB changed?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/JeffersonLab/rcdb/issues/34#issuecomment-221650477>
>

-- 
marki@jlab.org, (757)269-5295

**Comment by sdobbs** [comment]
Yes, I tried to change it from the counting house

**Comment by markito3** [comment]
A schema error is pretty fundamental. Something is really wrong... I'll 
ask Marty to check the server tomorrow, unless this needs to be 
addressed now. If now, that is do-able...

On 05/25/2016 05:26 PM, Sean Dobbs wrote:
> Yes, I tried to change it from the counting house
>
> On Wed, May 25, 2016 at 4:25 PM Mark M. Ito <notifications@github.com>
> wrote:
>
> > from the counting house? or from the computer center?
> >
> > On 05/25/2016 01:46 PM, Sean Dobbs wrote:
> > >
> > > Actually, i just tried to modify the DB from onsite, and also got a
> > > schema error. Maybe something in the DB changed?
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/JeffersonLab/rcdb/issues/34#issuecomment-221650477>
> > >
> >
> > --
> > marki@jlab.org, (757)269-5295
> >
> > —
> > You are receiving this because you commented.
> >
> >
> > Reply to this email directly or view it on GitHub
> > <https://github.com/JeffersonLab/rcdb/issues/34#issuecomment-221712552>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/JeffersonLab/rcdb/issues/34#issuecomment-221712716>
>

-- 
marki@jlab.org, (757)269-5295

**Comment by markito3** [comment]
Actually, I should have asked a more specific question. Did you try to 
change gluondb1?

On 05/25/2016 05:26 PM, Sean Dobbs wrote:
> Yes, I tried to change it from the counting house
>
> On Wed, May 25, 2016 at 4:25 PM Mark M. Ito <notifications@github.com>
> wrote:
>
> > from the counting house? or from the computer center?
> >
> > On 05/25/2016 01:46 PM, Sean Dobbs wrote:
> > >
> > > Actually, i just tried to modify the DB from onsite, and also got a
> > > schema error. Maybe something in the DB changed?
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/JeffersonLab/rcdb/issues/34#issuecomment-221650477>
> > >
> >
> > --
> > marki@jlab.org, (757)269-5295
> >
> > —
> > You are receiving this because you commented.
> >
> >
> > Reply to this email directly or view it on GitHub
> > <https://github.com/JeffersonLab/rcdb/issues/34#issuecomment-221712552>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/JeffersonLab/rcdb/issues/34#issuecomment-221712716>
>

-- 
marki@jlab.org, (757)269-5295

**Comment by sdobbs** [comment]
OK, this is confusing.  I was trying to change gluondb1, but was getting the error since I wasn't including the password correctly.  So the error is confusing.

When I try to run the example example_simple_queries.py in the counting house, it works if I supply the password, but throws the same schema error if I don't supply the password. Probably if I'm just querying the DB I shouldn't have to give a password?

If I try to connect from NU, I get the same schema error no matter if I give the password or not.

My suspicion is that this is some weird SQLAlchemy problem, since I can connect to the MySQL DB from the command line, both hallddb and gluondb1, on and offsite.

**Comment by markito3** [comment]
Marty is going to resynch the outward facing server, RCDB-wise, sometime tomorrow.

**Comment by markito3** [comment]
From Marty Wise, this morning:

Mark,

There are definitely significant differences between rcdb on the internal vs. external servers. Replication itself shows no errors, and things are in sync -- at least the slave is at the same point in the file as the master. I also ran table checks on the rcdb tables which showed no problems. SO, the server thinks everything is OK, though it obviously is not.

We had some emails about differences between the two a few weeks ago (around 5/3), but I don't think we ever decided to actually do anything to re-sync. I don't know if the problems have worsened since then, or if your current reports are the result of the same problems that existed back then. As I recall, there were also some differences between gluondb1 and hallddb, but these were relatively small (if there is such a thing). So, the main problem seems to be between the internal and external versions of hallddb.

The DB server version we are currently running is the December 2014 release (5.5.41). The current release is 5.5.49. I scanned the changelog for the few releases following 5.5.41 for anything that might be replication related and didn't see anything obvious, but in many cases, it's difficult to envision what the impact might be of a change related to some underlying detail.

In the absence of any better ideas, it may be a good idea to update things to bring them current, and re-sync the slaves. This would not include gluondb1 since it is running RHEL6 and has MySQL 5.1.x installed via RPM.

In addition to the update and re-sync, I'd like to reduce the privs of the users who have "ALL PRIVILEGES" or "SUPER" privileges since these allow you to bypass the normal read-only flag set on the external server. Basically, only take away the SUPER priv. I don't have any specific evidence that anyone has changed the DB from the "read only" slave, but this is certainly one possible source of desynchronization that we could eliminate and, since it might not be obvious which of the servers you are connected to (its determined by which DNS server you are using -- internal or external), so I could imagine that a laptop connected to the writable server that is taken off site would then transparently connect to the read-only slave. So, processes that you might run could update the wrong DB without it being clear that it's done so. Removal of the SUPER priv would prevent this sort of thing.

What do you think? Getting things straightened out would take a half day or so... I could work to minimize the actual outage to any specific server to a fairly short period (maybe as little as 10 minutes or so... I'll have to think about it. I'm really swamped with other stuff right now, but this is not a good situation, so I'll make time as needed to work with you guys to get it ironed out... just let me know when I can do it. As usual, early mornings or weekends would be fine if that makes it easier for you or your users.

Marty

**Comment by mikestaib** [comment]
This is now working for me offsite after the fix from Marty. Closing this issue.

**Comment by markito3** [comment]
I can still comment  on a closed issue, right? ;-)

This from Marty:

Per the plan coordinated with Mark Ito for Hall D, I re-synchronized the
hallddb
hallddb-ext server with the master (hallddb) using the standard 
procedure --

Before starting, I set a maintenance window of 1 hour for the mariadb 
(MySQL) and replication services on hallddb-ext to prevent any 
spurious alerts from Nagios during the procedure.

1. took a read lock on the master server on all DBs
2. recorded the master binary log position and dumped the DB to a sql
   file (with mysqldump --all-databases  --master-data > dumpfile.sql
3. released the locks (locks were in effect for only a minute or two)
4. copied the file to the slave server
5. stopped the DB server.
6. Made a tar file archive of the current mariadb directory
7. edited the my.cnf file to add skip_slave_start = 1
8. started the slave server, confirmed that replication had not started
9. reloaded the dump file from the master
   * the dump file contained the directives to restore the slave
     log position.
   * the dump file contained directives to create DBs if needed, and
     remove any tables, then recreate them and load data
10. started replication on the slave
11. edited my.cnf to set skip_slave_start back to 0

I then reviewed the tables and DBs on the slave, comparing the
schema config and row counts, etc. to the equivalent data on the 
master. I checked about 20% of the tables on the server, including
the rcdb and MySQL DBs in particular and found that everything matched 
exactly.

I then made a small change on the master (removing SUPER privilege form 
the marki@localhost user and confirmed that this change was replicated 
to the slave as expected.

It appears that replication is running correctly and that the slave is 
now properly synchronized with its master. Overall, the procedure only
took about 20 minutes, and the DB server was actually unavailable for
only about half that time. The master was not writable (due to the locks
needed to create the dump file) for about 2 minutes shortly before 5:00.

I allowed the Nagios maintenance window to expire to re-enable alerts if 
problems are seen.

Please let me know if any problems are seen, in particular any 
divergence of the slave from the master.
